<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial.xacro" />

    <xacro:property name="chassis_length" value="0.4" />
    <xacro:property name="chassis_width" value="0.4" />
    <xacro:property name="chassis_height" value="0.1" />

    <!-- CHANGE THIS -->
    <xacro:property name="chassis_mass" value="1" />

    <xacro:property name="arm_mass" value="0.001" />


    <xacro:property name="wheel_length" value="0.02" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_offset_x" value="0.1" />
    <xacro:property name="wheel_offset_z" value="0.02" />
    <xacro:property name="wheel_seperation" value="0.3" />
    <xacro:property name="wheel_mass" value="0.2" />
    <xacro:property name="caster_wheel_mass" value="0.01" />
    <xacro:property name="caster_wheel_radius" value="0.05" />

    <link name="base_link"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0"/>
    </joint>
    <link name="base_footprint"/>
<!-- DE XE -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="${-chassis_length/2} 0 0"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <origin xyz="${chassis_width/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size= "${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="red"/>
        </visual>

        <collision>
            <origin xyz="${chassis_width/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size= "${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/Red</material>
    </gazebo>

<!-- WHEEL -->
<!-- LEFT WHEEL -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${wheel_seperation/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <!-- axis of rotation -->
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

<!-- RIGHT WHEEL -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 -${wheel_seperation/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>  
        <!-- axis of rotation -->
    </joint>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <gazebo reference="right_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

<!-- CASTER WHEELS -->

    <joint name="caster_wheel_joint_front" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_front"/>
        <origin xyz="0.15 0 0" rpy="0 0 0"/>
    </joint>

    <link name="caster_wheel_front">
        <visual>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
        </collision>

        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_front">
        <material>Gazebo/Black</material>
        <mu1 value="0.01"/>
        <mu2 value="0.01"/>
    </gazebo>

    <joint name="caster_wheel_joint_back" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_back"/>
        <origin xyz="-0.15 0 0" rpy="0 0 0"/>
    </joint>

    <link name="caster_wheel_back">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_back">
        <material>Gazebo/Black</material>
        <mu1 value="0.01"/>
        <mu2 value="0.01"/>
    </gazebo>

</robot>